<style>
    .dataTables_filter{
        display:none;
    }
    #datatable_length {
        width: 92%;
    }
</style>
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    
                    <div class="col-md-4">
                        <span style="font-size: 16px;">
                            <b>Invoice</b>
                        </span>
                    </div>
                    
                    <div class="col-md-4">
                        <span style="font-size: 16px;">
                            <b>Un-Billed Amount</b>
                        </span><br/>
                       <span data-toggle="modal" data-target="#myModal2" style="color:red; font-size: 16px; cursor: pointer;">
                            <b>Rs. <?php echo round($unbilled_amount,0);?> 
                                <i class="fa fa-info-circle" aria-hidden="true"></i>
                            </b>
                       </span>
                    </div>
                    
                    <div class="col-md-4">
                        <span style="font-size: 16px;">
                            <b><?php if($invoice_amount['final_amount'] > 0){ echo "Un-Settle Amount";} else { echo "Balanced Amount";}?></b>
                        </span><br/>
                        <span style="<?php if($invoice_amount['final_amount'] > 0){ echo "color:red;";} else { echo "color:green;";}?> font-size: 16px;">
                            <b>Rs.<?php echo abs(round($invoice_amount['final_amount'],0));?></b>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <table class="table table-bordered table-hover table-striped data" id="datatable">
                        <thead>
                            <tr >
                                <th>S.N</th>
                                <th>Invoice ID</th>
                                <th>Invoice Generated By</th>
                                <th>Invoice Date</th>
                                <th>Invoice Period</th>
                                <th>Category</th>
                                <th>Bookings/ Parts</th>
                                 <th>TDS</th>
                                <th>Total Invoice Amount</th>

                                <th>Paid Amount</th>
                                <th>Balance</th>
                                <th>Download</th>
                            </tr>
                        </thead>
<!--                        <tbody>
                            <?php
                                //if (!empty($invoice_array)) {
                                   // foreach ($invoice_array as $key => $invoice) {
                                        ?>
                            <tr <?php //if ($invoice['settle_amount'] == 1) { ?> style="background-color: #90EE90; " <?php //} ?>>
                                <td><?php //echo ($key + 1); ?></td>
                                <td>
                                    <?php //echo $invoice["invoice_id"]; ?>
                                </td>
                                <td><?php //echo date("jS M, Y", strtotime($invoice['invoice_date'])); ?></td>
                                <td><?php //echo date("jS M, Y", strtotime($invoice['from_date'])) . " to " . date("jS M, Y", strtotime($invoice['to_date'])); ?></td>
                                <td><?php //echo $invoice['num_bookings'] . "/" . $invoice['parts_count']; ?></td>
                                <td><?php //echo $invoice['total_amount_collected']; ?></td>
                                <td>
                                    <ul style=" list-style-type: none;">
                                        <?php //if(!empty($invoice['invoice_file_main'])) { ?><li style="display: inline; font-size: 30px;"><a title="Main File"  href="https://s3.amazonaws.com/<?php //echo BITBUCKET_DIRECTORY; ?>/invoices-excel/<?php //echo $invoice['invoice_file_main']; ?>"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a></li><?php //} ?>
                                         <?php //if(!empty($invoice['invoice_detailed_excel'])) { ?><li style="display: inline;font-size: 30px; margin-left: 10px;"><a  href="https://s3.amazonaws.com/<?php //echo BITBUCKET_DIRECTORY; ?>/invoices-excel/<?php //echo $invoice['invoice_detailed_excel']; ?>"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a></li><?php //} ?>
                                    </ul>
                                </td>
                                <?php ?>
                            </tr>
                            <?php
                                //}
                                //}
                                ?>
                        </tbody>-->
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div id="myModal2" class="modal fade" role="dialog">
      <div class="modal-dialog modal-lg">
         <!-- Modal content-->
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
               <h4 class="modal-title" id="modal-title">Unbilled Booking</h4>
               <h6>Note: Upcountry Charges are not included in the below booking</h6>
            </div>
            <div class="modal-body">
                <table class="table table-bordered table-hover table-striped data" id="unbilled_table">
                    <thead>
                    <th>Booking ID</th>
                    <th>Charges</th>
                    <th>Booking Status</th>
                    <th>Registration</th>
                    </thead>
                    <tbody>
                        <?php foreach ($unbilled_data as $key => $value) { ?>              
                        <tr>
                            <td><?php echo $value['booking_id']; ?></td>
                            <td><?php echo $value['partner_net_payable'] *(1 + SERVICE_TAX_RATE); ?></td>
                            <td><?php echo $value['booking_status'];?></td>
                            <td><?php echo date("jS M, Y", strtotime($value['create_date']));?></td>
                        </tr>
                        <?php }?>
                        <?php if($misc) { foreach ($misc as $m) { ?>
                             <tr>                               
                                                           
                                 <td style="max-width:150px;"><?php echo $m['booking_id']." (".$m['description'].")"; ?></td>
                                <td><?php echo round($m['partner_charge'] *(1 + SERVICE_TAX_RATE),0); ?></td>
                                <td><?php echo $m['current_status'];?></td>
                                <td><?php echo date("jS M, Y", strtotime($m['create_date'])); ?></td>
                             </tr>

                        <?php } }?>
                        <?php if($upcountry > 0){ ?>
                            <tr>
                            <td><?php echo "Upcountry Charges"; ?></td>
                            <td><?php echo round($upcountry *(1 + SERVICE_TAX_RATE),0); ?></td>
                            <td></td>
                            <td></td>
                            
                            </tr>
                        <?php }?>
                        
                    </tbody>
                </table>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" onclick="close_model()">Close</button>
            </div>
         </div>
      </div>
   </div>    
</div>
<script>
    var invoice_table = null;
    $(document).ready(function () {
         loaddataTable();
    });
    
    $("#unbilled_table").DataTable({
         dom: 'lBfrtip',
         "lengthMenu": [[-1], ["All"]],
          buttons: [
                {
                    extend: 'excel',
                    text: '<span class="fa fa-file-excel-o"></span> Excel Export',
                    pageSize: 'LEGAL',
                    title: 'Un-billed Invoice',
                    exportOptions: {
                       columns: [0,1,2,3],
                        modifier : {
                             // DataTables core
                             order : 'index',  // 'current', 'applied', 'index',  'original'
                             page : 'All',      // 'all',     'current'
                             search : 'none'     // 'none',    'applied', 'removed'
                         }
                    }
                    
                }
            ],
        columnDefs: [
                {
                    targets: [0,1,2,3], //first column / numbering column
                    orderable: false //set not orderable
                }
            ],
    });
    function loaddataTable(){
        invoice_table = $('#datatable').DataTable({
         "processing": true, //Feature control the processing indicator.
         "serverSide": true, //Feature control DataTables' server-side processing mode.
         "order": [[ 1, "desc" ]], //Initial no order.
         "pageLength": 50,
          dom: 'lBfrtip',
         "lengthMenu": [[10, 25, 50,100, -1], [10, 25, 50, 100,"All"]],
          buttons: [
                {
                    extend: 'excel',
                    text: '<span class="fa fa-file-excel-o"></span> Excel Export',
                    pageSize: 'LEGAL',
                    title: 'Invoice',
                    exportOptions: {
                       columns: [1,2,3,4,5,6,7,8,9],
                        modifier : {
                             // DataTables core
                             order : 'index',  // 'current', 'applied', 'index',  'original'
                             page : 'All',      // 'all',     'current'
                             search : 'none'     // 'none',    'applied', 'removed'
                         }
                    }
                    
                }
            ],
         // Load data for the table's content from an Ajax source
            ajax: {
                url: "<?php echo base_url();?>employee/accounting/get_invoice_searched_data",
                type: "POST",
                data: function(d){

                        d.request_type = "partner_invoice_summary";
                        d.vendor_partner = 'partner';
                        d.vendor_partner_id = '<?php echo $this->session->userdata('partner_id') ?>';
                        d.settle = '2';
                 }

            },

            //Set column definition initialisation properties.
            columnDefs: [
                {
                    targets: [0,1,2,3,4,5,6,7,8,9,10,11], //first column / numbering column
                    orderable: false //set not orderable
                }
            ],
            fnInitComplete: function (oSettings, response) {
                $('#datatable tr span.satteled_row').each(function(){ $(this).closest('tr').css("background-color", "#90EE90");  });
          }

     });
    }
    
    $("#datatable").bind("DOMSubtreeModified", function() {
        $('#datatable tr span.satteled_row').each(function(){ $(this).closest('tr').css("background-color", "#90EE90");  });
    });
</script>