<?php
$qr_message="{qr_message}";
$booking_id=3112;
$name="{name}";
$booking_primary_contact_no="{booking_primary_contact_no}";
$booking_alternate_contact_no="{booking_alternate_contact_no}";
$services="{services}";
$order_id="{order_id}";
$booking_address="{booking_address}";
$city="{city}";
$state="{state}";
$booking_pincode="{booking_pincode}";
$booking_date="{booking_date}";
$booking_timeslot="{booking_timeslot}";
$appliance_description="{appliance_description}";
$booking_remarks="{booking_remarks}";
$appliance_category="sdss";
$appliance_capacity="xcxzc";
$appliance_brand="dvsc";
$model_number="czc";
$price_tags="dsd";
$customer_net_payable=13132;
$i=1;
$total=0;
$upcountry_charges=223;
$record=array(array("part_no"=>231,"description"=>"description","qty"=>6,"unit_price"=>23),
				array("part_no"=>231,"description"=>"description","qty"=>6,"unit_price"=>23));
?>