<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
define('CUSTOMER_UPDATE_BOOKING_PUSH_NOTIFICATION_EMPLOYEE_TAG','sf_updates_the_booking');
define('BOOKING_ASSIGN_TO_VENDOR','booking_assign_to_sf');
define('BOOKING_UPDATED_BY_247AROUND','booking_updated_by_247Around');
define('BOOKING_COMPLETED_FOR_PARTNER','booking_completed_for_partner');
define('NEW_BOOKING_FOR_PARTNER','new_booking_from_partner');
define('NEW_PINCODE_ADDED','new_pincode_added');
define('PAN_DETAILS_REQUEST','pan_details_request');
define('GST_DETAILS_REQUEST','gst_details_request');
define('BANK_DETAILS_REQUEST','bank_details_request');
define('BOOKING_ESCALATION_VENDOR','booking_escalation_to_vendor');
define('PENDING_SPARE_VENDOR','pending_spare_part_to_vendor');
define('UPDATE_BOOKING_TO_AVOID_PENALTY','update_booking_request_vendor');
define('LOW_PREPAID_AMOUNT','low_prepaid_amount');
define('SPARE_PART_REQUEST_TO_PARTNER','spare_part_request_to_partner');
define('UPCOUNTRY_APPROVAL','upcountry_approval_partner');
define('INVOICE_CREATED_PARTNER','invoice_created_partner');
define('PENDING_SPARE_PARTS_TO_PARTNER','pending_spare_part_to_partner');
define('PENDING_INVOICES_TO_PARTNERS_POSTPAID','pending_invoices_to_postpaid_partners');
define('NOTIFICATIONS_CENTER_LIMIT','25');
// Add comma Seprated Id if you want to send notification to more then 1 employee
define('INSTALLATION_MISSED_CALL_NOTIFICATION_EMPLOYYE_IDS','22');
define('INSTALLATION_MISSED_CALL_NOTIFICATION','installation_missed_call');
define('POOR_RATING_MISSED_CALL_NOTIFICATION_EMPLOYYE_IDS','19');
define('POOR_RATING_MISSED_CALL_NOTIFICATION','poor_rating_missed_call');
define('INVALID_SUBSCRIBER_ID_MSG','Invalid Subscriber IDs found in subscriber list.');
define('PUSH_NOTIFICATION_ERROR_NOTIFY_EMAIL','247around_dev@247around.com');