<?php

/* 
 * Constants for Rabbitmq Library
 */
require_once __DIR__ . '/../../vendor/autoload.php';

define('RABBITMQ_HOST', 'localhost');
define('RABBITMQ_PORT', 5672);
define('RABBITMQ_USER', '247around');
define('RABBITMQ_PASS', '6NDb6z7l#%i$sMlq');
define('RABBITMQ_VHOST', '/');
define('RABBITMQ_AMQP_DEBUG', false);


define('RABBITMQ_EXCHANGE_DEFAULT', '247around');
define('RABBITMQ_QUEUE_SMS', '247around-Queue-SMS');

define('RABBITMQ_QUEUE_DECLARE_PASSIVE_TRUE', TRUE);
define('RABBITMQ_QUEUE_DECLARE_PASSIVE_FALSE', false);
define('RABBITMQ_QUEUE_DECLARE_DURABLE_TRUE', TRUE);
define('RABBITMQ_QUEUE_DECLARE_DURABLE_FALSE', false);
define('RABBITMQ_QUEUE_DECLARE_EXCLUSIVE_TRUE', TRUE);
define('RABBITMQ_QUEUE_DECLARE_EXCLUSIVE_FALSE', false);
define('RABBITMQ_QUEUE_DECLARE_AUTODELETE_TRUE', TRUE);
define('RABBITMQ_QUEUE_DECLARE_AUTODELETE_FALSE', false);

define('RABBITMQ_EXCHANGE_DECLARE_PASSIVE_TRUE', TRUE);
define('RABBITMQ_EXCHANGE_DECLARE_PASSIVE_FALSE', false);
define('RABBITMQ_EXCHANGE_DECLARE_DURABLE_TRUE', TRUE);
define('RABBITMQ_EXCHANGE_DECLARE_DURABLE_FALSE', false);
define('RABBITMQ_EXCHANGE_DECLARE_AUTODELETE_TRUE', TRUE);
define('RABBITMQ_EXCHANGE_DECLARE_AUTODELETE_FALSE', false);

define('RABBITMQ_CHANNEL_CONSUME_NOLOCAL_TRUE', TRUE);
define('RABBITMQ_CHANNEL_CONSUME_NOLOCAL_FALSE', FALSE);
define('RABBITMQ_CHANNEL_CONSUME_AUTOACK_TRUE', TRUE);
define('RABBITMQ_CHANNEL_CONSUME_AUTOACK_FALSE', FALSE);
define('RABBITMQ_CHANNEL_CONSUME_EXCLUSIVE_TRUE', TRUE);
define('RABBITMQ_CHANNEL_CONSUME_EXCLUSIVE_FALSE', FALSE);
define('RABBITMQ_CHANNEL_CONSUME_NOWAIT_TRUE', TRUE);
define('RABBITMQ_CHANNEL_CONSUME_NOWAIT_FALSE', FALSE);
