<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//Knowlarity Credentials
define('KNOWLARITY_APPLICATION_KEY', 'L2WufpUCXD5kkFiCSDzHh1FafEVUsR4M5CNaiID3');
define('KNOWLARITY_API_KEY', '925e6a88-be5e-408b-b211-58bd1a09a63c');
define('KNOWLARITY_NUMBER', '+918971877477');
define('KNOWLARITY_OUTGOING_CALL_URL', 'https://kpi.knowlarity.com/Basic/v1/account/call/makecall');
define('KNOWLARITY_CALL_LOG_URL', 'https://kpi.knowlarity.com/Basic/v1/account/calllog');

define('PARTNERS_MISSED_CALLED_NUMBER_KNOWLARITY','01143092150');
define('SNAPDEAL_MISSED_CALLED_NUMBER_KNOWLARITY','01143092150');
define('AC_SERVICE_MISSED_CALLED_NUMBER_KNOWLARITY','01143092150');
define('ANDROID_APP_MISSED_CALLED_NUMBER_KNOWLARITY','01143092150');
define('GOOD_MISSED_CALL_RATING_NUMBER_KNOWLARITY','01130017603');
define('POOR_MISSED_CALL_RATING_NUMBER_KNOWLARITY','01143092150');
define('FAKE_RESCHEDULED_MISSED_CALL_NUMBER_KNOWLARITY','01130017609');
define('CURRENT_TELEPHONY_SOLUTION','EXOTEL');      
define('CURRENT_SMS_SOLUTION','EXOTEL');      
define('KNOWLARITY_STRING','KNOWLARITY');
define('EXOTEL_STRING','EXOTEL');
define('KNOWLARITY_SMS_URL',"https://entp-apis.knowlarity.com/prod_sms/entp-sms/messenger_app/generic");
define('KNOWLARITY_SMS_AUTH_KEY',"8b89e0a5-9c0a-11e8-8f5a-02d35676b79a");
define('KNOWLARITY_CLIENT_ID',"Around");
define('KNOWLARITY_PASSPHRASE',"AROUND18");
define('KNOWLARITY_SENDER_ID',"AROUND");


