ALTER TABLE `spare_parts_details` ADD `courier_rejection_remarks` VARCHAR(260) NULL DEFAULT NULL AFTER `remarks_defective_part_by_sf`;

UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION VERY RUSTING' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PART CONDITION NOT GOOD' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET AND CORRECT DOCKET IMAGE WITHOUT AMOUNT ONLY PUT UP 0' WHERE spare_parts_details.id =44081;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'part condition not good every time reject in my side, please send actual and good condition parts then after I have approved' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE SEND ORIGINAL BRAND DEFECTIVE PARTS' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET IMAGE WITH RS 0 ALSO' WHERE spare_parts_details.id =121673;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '9TH TIMES REJECTED' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '11TH TIMES REJECTED' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '13TH TIMES REJECTED' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '12th Times Rejected' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE WAREHOUSE RECEIVING COPY WITH BOOKING ID DETAIL UPDATE THEN AFTER I HAVE APPROVED ALL BOOKING ID' WHERE spare_parts_details.id =83063;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE WAREHOUSE RECEIVING COPY WITH BOOKING ID DETAIL UPDATE THEN AFTER I HAVE APPROVED ALL BOOKING ID' WHERE spare_parts_details.id =83063;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE WAREHOUSE RECEIVING COPY WITH BOOKING ID DETAIL UPDATE THEN AFTER I HAVE APPROVED ALL BOOKING ID' WHERE spare_parts_details.id =52547;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '19TH TIMES REJECTED' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '1st in the warehouse then clear all dispute' WHERE spare_parts_details.id =208294;
UPDATE spare_parts_details SET courier_rejection_remarks = '1ST IN WAREHOUSE THEN APPROVED ALL PARTS OTHERWISE EVERYTIME I HAVE REJECTED ALL YOUR PARTS' WHERE spare_parts_details.id =208294;
UPDATE spare_parts_details SET courier_rejection_remarks = '1ST IN WAREHOUSE AND 1ST OUT ALL DISPUTE ISSUE' WHERE spare_parts_details.id =208294;
UPDATE spare_parts_details SET courier_rejection_remarks = '1ST IN WAREHOUSE 2ND DISPUTED ALL CLEAR' WHERE spare_parts_details.id =208294;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the full docket copy image not update the screenshot for the docket image and update also rs 0' WHERE spare_parts_details.id =198000;
UPDATE spare_parts_details SET courier_rejection_remarks = '1ST IN WAREHOUSE 2ND ALL ISSUE RESOLVE WAREHOUSE TEAM' WHERE spare_parts_details.id =208294;
UPDATE spare_parts_details SET courier_rejection_remarks = '1st in 1st out issue' WHERE spare_parts_details.id =208294;
UPDATE spare_parts_details SET courier_rejection_remarks = '1ST IN 1ST OUT WAREHOUSE PARTS ISSUE' WHERE spare_parts_details.id =208294;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET IMAGE THAN AFTER HAVE APPROVED' WHERE spare_parts_details.id =174720;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '37TH TIMES REJECTED, 1ST COME IN WAREHOUSE THEN RESOLVED THIS ISSUE' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '38th times rejected, please comes in the warehouse and shootout your all Issue' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 40 TIMES' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 41 TIMES' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = '42 TIMES REJECTED' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 43 TIMES' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 44 TIMES' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 45 TIMES' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =78082;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 46 TIMES' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =78082;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 48 TIMES' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 49TH TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 49TH TIMES' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 49TH TIMES' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =78082;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Rejected 49th Times' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =73913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =78082;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =78082;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 50TH TIMES GOLDEN JUBLEE' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE DOCKET NO AND AMOUNT SHOULD BE FILL 0 OR 01, NOT FILL ABOVE, AND AWB NO AGAINST SPOTON' WHERE spare_parts_details.id =222968;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET IMAGE AND NUMBER' WHERE spare_parts_details.id =57127;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET IMAGE AND NUMBER' WHERE spare_parts_details.id =115439;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET IMAGE AND NUMBER' WHERE spare_parts_details.id =223883;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =78082;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =85701;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =117960;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =69068;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =77767;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =116257;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =163023;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =141076;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =175551;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =136496;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED 52 TIMES, ANY DISCUSSION PLEASE CONTACT TO NARAYAN SIR' WHERE spare_parts_details.id =184118;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET' WHERE spare_parts_details.id =134305;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET IMAGE AND NUMBER' WHERE spare_parts_details.id =159222;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET IMAGE AND NUMBER' WHERE spare_parts_details.id =223948;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT RECEIVING COPY, THIS COPY  NOT MENTION BOOKING ID' WHERE spare_parts_details.id =90240;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET' WHERE spare_parts_details.id =229398;
UPDATE spare_parts_details SET courier_rejection_remarks = 'THIS DOCKET BEHALF PICKUP NOT DONE TILL DATE PLEASE CORRECT DOCKET' WHERE spare_parts_details.id =226149;
UPDATE spare_parts_details SET courier_rejection_remarks = 'Please update the correct docket and filling correct price' WHERE spare_parts_details.id =243629;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE MENTION AMOUNT DOCKET SLIP THEN AFTER UPDATE THIS DOCKET' WHERE spare_parts_details.id =243629;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE ON CORRECT AND FULL FILL DOCKET COPY' WHERE spare_parts_details.id =244243;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE DOCKET WITH PRICE' WHERE spare_parts_details.id =243629;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE DOCKET WITH PRICE' WHERE spare_parts_details.id =243629;
UPDATE spare_parts_details SET courier_rejection_remarks = 'DOCKET CHARGE NOT MENTION IN DOCKET COPY' WHERE spare_parts_details.id =173939;
UPDATE spare_parts_details SET courier_rejection_remarks = 'REJECTED' WHERE spare_parts_details.id =173939;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET AND RECEIVING COPY' WHERE spare_parts_details.id =61189;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE DOCKET WITH PRICE' WHERE spare_parts_details.id =243629;
UPDATE spare_parts_details SET courier_rejection_remarks = 'DOCKET PAR PAISA UPDATE NAHI HAI ISILIYE REJECT MAR RAHA HU' WHERE spare_parts_details.id =173939;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE FULL COURIER SLIP WITH AMOUNT MENTION IN SLIP' WHERE spare_parts_details.id =241526;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE FULL COURIER SLIP WITH AMOUNT MENTION IN SLIP' WHERE spare_parts_details.id =214446;
UPDATE spare_parts_details SET courier_rejection_remarks = 'UPDATE CORRECT ANY ISSUE NOW CALL ME 9773618247' WHERE spare_parts_details.id =173939;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT DOCKET WITH WEIGHT AND PRICE NOT MENTION IN SLIP' WHERE spare_parts_details.id =192113;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PRICE NOT MENTION IN DOCKET SLIP' WHERE spare_parts_details.id =259718;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =86846;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =89328;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =121020;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =121905;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE the CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =132991;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE the CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =147153;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE the CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =152407;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE the CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =161750;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE the CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =229105;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE the CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =231617;
UPDATE spare_parts_details SET courier_rejection_remarks = 'PLEASE UPDATE the CORRECT IMAGE FOR RECEIVED SHIPMENT' WHERE spare_parts_details.id =157044;
UPDATE spare_parts_details SET courier_rejection_remarks = 'DOCKET NOT TRACK AT COURIER SITE' WHERE spare_parts_details.id =228130;
UPDATE spare_parts_details SET courier_rejection_remarks = 'DOCKET NOT TRACK AT COURIER SITE' WHERE spare_parts_details.id =243913;
UPDATE spare_parts_details SET courier_rejection_remarks = 'DOCKET NOT TRACK AT COURIER SITE' WHERE spare_parts_details.id =239730;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =86846;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =89328;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =121905;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =121020;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =132991;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =147153;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =161750;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =229105;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =229105;
UPDATE spare_parts_details SET courier_rejection_remarks = 'please update the correct receiving copy then after update in CRM' WHERE spare_parts_details.id =231617;
